# Generated by Django 6.0.1 on 2026-02-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('travel_days', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('file_url', models.URLField()),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='pt', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
