# Generated by Django 6.0.1 on 2026-02-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
